Render Toolbox 3: Utilities
Utilities
Miscellaneous utilities.
Functions
CleanMatlabPath ()
Remove '.svn' and '.git' folders from the Matlab path.
ColladaToMitsuba (colladaFile, mitsubaFile, adjustmentsFile, hints)
Convert a Collada scene file to a Mitusuba scene file.
ColladaToPBRT (colladaFile, pbrtFile, adjustmentsFile, hints)
Convert a Collada scene file to a PBRT scene file.
ColorimetricMatToTextFiles (inFile, outDir, outBase, outExt)
Convert colorimetric data from a .mat file to multiple text files.
fileList FindFiles (folder, fileFilter, isFolders)
Locate files at or below the given folder.
wavelengths magnitudes sRGB GetPixelSpectrum (image, spectrum, x, y)
Get wavelengths and magnitudes from a multispectral image pixel.
InitializeRenderToolbox (isForce)
Create Matlab preferences for RenderToolbox3.
isPresent IsStructFieldPresent (s, fieldName)
Does a struct have a particular field?
isClockwise IsVerticesClockwise (vertices)
Check the winding order of vertices in 3D space.
SRGBImage XYZImage rawImage MultispectralToSRGB (multispectralImage, S, toneMapFactor, isScale)
Convert multi-spectral image data to XYZ and sRGB.
numbers nNums ReadStringNumbers (string, nGrouping)
Read numbers from a string, with optional grouping.
rootPath RenderToolboxRoot ()
Get the path to RenderToolbox3.
status result output RunMitsuba (sceneFile, isShow)
Invoke the Mitsuba renderer.
status result output RunPBRT (sceneFile, isShow)
Invoke the PBRT renderer.
ShowXYZAndSRGB (XYZImage, SRGBImage, name)
Plot XYZ and sRGB image representations.
nX nY nZ edges ShowXYZHistogram (XYZImage, nEdges)
Plot histograms for XYZ image components.
vector StringToVector (string)
Convert a string representation of numbers to a 1D matrix.
string VectorToString (vector)
Convert a 1D matrix of numbers to string representation.
gammaImage rawImage XYZToSRGB (XYZImage, toneMapFactor, toneMapMax, isScale)
Convert an image in XYZ colors to sRGB colors.
Detailed Description
Miscellaneous utilities.
Function Documentation
CleanMatlabPath ()
Remove '.svn' and '.git' folders from the Matlab path.
Modifies the Matlab path, removing path entries that contain '.git' or '.svn'. You should save the path afterwards. You can use this function while the Matlab "Set Path" dialog is open!
Usage: CleanMatlabPath()
ColladaToMitsuba (colladaFile , mitsubaFile , adjustmentsFile , hints)
Convert a Collada scene file to a Mitusuba scene file.
Parameters
colladaFile input Collada file name or path
mitsubaFile output Mitsuba file name or path (optional)
adjustmentsFile adjustments file name or path (optional)
hints struct of hints from GetDefaultHints() (optional)
Converts the given colladaFile ('.dae' or '.xml') to a mitsuba .xml file with the name (and path) given in mitsubaFile.
If adjustmentsFile is provided, it should be the name of a partial Mitsuba scence file in .xml format. Elements of adjustmentsFile will replace or modify elements of the converted scene file according to matching "id" attributes.
Note that RenderToolbox3 uses a custom mechanism for applying adjustments to Mitsuba scenes, instead of the built-in Mitusba mechanism. This allows finer-grained adjustments to scene elements.
hints may be a struct with additional parameters for the converter. See GetDefaultHints() for more about batch renderer hints.
Usage: ColladaToMitsuba(colladaFile, mitsubaFile, adjustmentsFile, hints)
References GetDefaultHints(), MergeAdjustments(), ReadSceneDOM(), and WriteSceneDOM().
Referenced by BatchRender().
ColladaToPBRT (colladaFile , pbrtFile , adjustmentsFile , hints)
Convert a Collada scene file to a PBRT scene file.
Parameters
colladaFile input Collada file name or path
pbrtFile output PBRT file name or path (optional)
adjustmentsFile adjustments file name or path (optional)
hints struct of hints from GetDefaultHints() (optional)
Converts the given colladaFile ('.dae' or '.xml') to a PBRT .pbrt file with the name (and path) given in pbrtFile.
If adjustmentsFile is provided, it should be the name of a PBRT-XML adjustments file in .xml format. Elements of adjustmentsFile will replace or modify elements of the converted scene file according to matching "id" attributes.
hints may be a struct with additional parameters for the converter. See GetDefaultHints() for more about batch renderer hints.
Usage: ColladaToPBRT(colladaFile, pbrtFile, adjustmentsFile, hints)
References CreateStubDOM(), GetDefaultHints(), MergeAdjustments(), PopulateStubDOM(), ReadSceneDOM(), WritePBRTFile(), and WriteSceneDOM().
Referenced by BatchRender().
ColorimetricMatToTextFiles (inFile , outDir , outBase , outExt)
Convert colorimetric data from a .mat file to multiple text files.
Parameters
inFile input .mat file with colorimetric data
outDir output folder for text files (optional)
outBase stem for output file names (optional)
outExt extension for output file names (optional)
Converts colorimetric data from the given inFile .mat file to multiple text files which are formatted for use by PBRT and Mitsuba.
inFile should be the name of a .mat file which obeys Psychtoolbox colorimetric mat file conventions. The name should use a prefix, followed by an underscore, followed by a descriptive name. For example, RenderToolbox includes "sur_mccBabel.mat": "sur" is the prefix, "mccBabel" is the descriptve name.
inFile should contain two variables. The first should have the same name as inFile, minus the ".mat". For example, "sur_mccBabel.mat" contains the variable "sur_mccBabel". This variable should be an m x n matrix of colorimatric data points, where m is the number of samples taken across the spectrum, and n is the number of different objects measured.
The second variable should be named like the inFile, but with an "S" instead of the original prefix. For example, "sur_mccBabel.mat" contains the variable "S_mccBabel". This variable describes the samples taken across the spectrum. It has the format [start delta m], where start and delta are wavelenghts in nanometers and m is the number of samples taken across the spectrum.
Produces multiple text files in the given outDir, with each file name starting with the given outBase and ending with the given outExt. If there are multiple objects measured (n > 1) each filename will contain a numeric suffix. For example, "sur_mccBabel.mat" might produce a file named "mccBabel-24.spd". If outDir is omitted, pwd() is used instead. If outBase is omitted, an output name is chosen automatically based on inFile. If outExt is omitted, ".spd" is used.
Usage: ColorimetricToSPDFiles(inFile, outDir, outBase, outExt)
fileList FindFiles (folder , fileFilter , isFolders)
Locate files at or below the given folder.
Parameters
folder path where to start looking for files
filter optional regular expression for filtering files
FindFiles() recursively searches folder and its subfolders for files. If folder is omitted, uses pwd(). By default, returns all files. fileFilter may contain a regular expression, in which case only files whose names match are included. Matching is performed on full, absolute path names.
By default, only returns file names, not folder names. If isFolders is provided and true, returns folder names as well as file names.
Ignores subfolders that contain '.'. Ignores files that start with '.' or end with "~" or "ASV".
Returns a cell array of string which are the full, absolute path names of files that were found and matched.
Usage: fileList = FindFiles(folder, fileFilter, isFolders)
Referenced by WriteDefaultMappingsFile().
wavelengths magnitudes sRGB GetPixelSpectrum (image , spectrum , x , y)
Get wavelengths and magnitudes from a multispectral image pixel.
Parameters
image multispectral image matrix of size [height width n]
spectrum description of the n spectrum bands of image
x x-coordinate of the pixel to probe
y y-coordinate of the pixel to probe
Gets the spectral magnitude distribution of one pixel in the given multi-spectral image.
image must be a multi-spectral image matrix, with size [height width n], where height and width are the image pixel dimensions, and n is the number of spectrum bands in the image.
spectrum must be a description of the n spectrum bands in image. spectrum may be a 1 x n list of wavelengths, or it may be an "S" description of the form [start delta n], where start is the wavelength of the lowest spectrum band, and delta is the width of each band.
x and y must be the x-coordinage and y-coordinate of the pixel of interest.
Returns a 1 x n matrix of n wavelengths, and a corresponding 1 x n matrix of magnitudes, for the pixel of interest. Also returns an sRGB approximation of the spectrum of the pixel of interest.
Usage: [wavelengths, magnitudes, sRGB] = GetPixelSpectrum(image, spectrum, x, y)
References MultispectralToSRGB().
InitializeRenderToolbox (isForce)
Create Matlab preferences for RenderToolbox3.
Parameters
isForce whether to create preferences from scratch (optional)
Chooses paths and other constants related to the Mitsuba and PBRT renderers, and makes these available with Matlab's setpref() and getpref() functions. Also sets the PATH environment variable, as used by the Matlab unix() command, to contain the paths to each renderer's executable.
To see the paths and constants for each renderer, try:
InitializeRenderToolbox(true);
MitsubaPrefs = getpref('Mitsuba')
PBRTPrefs = getpref('PBRT')
You should set the paths to Mitsuba and PBRT on your machine:
% Mitsuba on OS X
setpref('Mitusba', 'app', path-to-Mitsuba);
% Mitsuba on other platforms
setpref('Mitusba', 'app', '');
setpref('Mitusba', 'executable', path-to-Mitsuba-executable);
setpref('Mitusba', 'importer', path-to-Mitsuba-importer);
% PBRT
setpref('PBRT', 'executable', path-to-PBRT);
By default, leaves any existing RenderTooblox3 preferences in place. If isForce is provided and true, replaces existing preferences with default values.
Usage: InitializeRenderToolbox(isForce)
References RenderToolboxRoot().
Referenced by BatchRender(), RunMitsuba(), and RunPBRT().
isPresent IsStructFieldPresent (s , fieldName)
Does a struct have a particular field?
Parameters
s a struct
fieldName string field name
Returns true if the given s has a field with the given fieldName, and if the field is not empty. Otherwise returns false.
Usage: isPresent = IsStructFieldPresent(s, fieldName)
Referenced by GetDefaultHints().
isClockwise IsVerticesClockwise (vertices)
Check the winding order of vertices in 3D space.
Parameters
vertices m x 3 matrix of XYZ triples
Returns true if the given vertices are wound in clockwise order. For porposes of this function, "clockwise" is defined arbitrarily and it's only meaningful to compare sets of vertices for differences in winding order.
vertices should contain at least 3 XYZ triples. Only the first 3 will be checked for winding order. Subtracts the first vertex from each of the nest two vertices, and takes the cross product of the differences. If the product has a non-negative z-component, vertices are "clockwise". Otherwise they're "counter-clockwise".
Returns true if vertices are wound in clockwise order.
Usage: isClockwise = IsVerticesClockwise(vertices)
SRGBImage XYZImage rawImage MultispectralToSRGB (multispectralImage , S , toneMapFactor , isScale)
Convert multi-spectral image data to XYZ and sRGB.
Parameters
multispectralImage
S
toneMapFactor
isScale
Convert the given multispectralImage of size [height width n] to an sRGB image of size [height width 3], for viewing on a standard monitor.
The given S must describe the n spectral planes of the multispectralImage. It should have the form [start delta n], where start and delta are wavelengths in nanometers, and n is the number of spectral planes.
If S toneMapFactor is provided and greater than 0, truncates luminances above this factor times the mean luminance.
If isScale is true, the gamma-corrected image will be scaled to use they gamma-corrected maximum.
Returns a gamma-corrected sRGB image of size [height width 3]. Also returns the intermediate XYZ image and the uncorrected RGB image, which have the same size.
Usage: [SRGBImage, XYZImage, rawImage] = MultispectralToSRGB(multispectralImage, S, toneMapFactor, isScale)
References XYZToSRGB().
Referenced by GetPixelSpectrum(), MakeMontage(), RunMitsuba(), and RunPBRT().
numbers nNums ReadStringNumbers (string , nGrouping)
Read numbers from a string, with optional grouping.
Parameters
string a string to scan for numbers
nGrouping how many numbers to include in each group (optional)
Reads decimal number representations from the given string. Returns numbers as separate elements of a cell array of strings. By default, each element of the cell array of strings will contain one number. If nGrouping is provided, each element will contain nGrouping numbers. Also returns the total count of numbers found in in the given string.
Usage: [numbers, nNums] = ReadStringNumbers(string, nGrouping)
References StringToVector(), and VectorToString().
rootPath RenderToolboxRoot ()
Get the path to RenderToolbox3.
Returns the absolute path to RenderToolbox3, based on the location of this file, RenderToolboxRoot.m.
Usage: rootPath = RenderToolboxRoot()
Referenced by BatchRender(), GetDefaultHints(), InitializeRenderToolbox(), MakeReadMultichannelEXR(), and WriteDefaultMappingsFile().
status result output RunMitsuba (sceneFile , isShow)
Invoke the Mitsuba renderer.
Parameters
sceneFile filename or path of a Mitsuba .xml scene file.
isShow whether or not to display the output image in a figure
Invoke the Mitsuba renderer on the given .xml sceneFile. This function handles some of the boring details of invoking Mitsuba with Matlab's unix() command.
if isShow is provided and true, displays an sRGB representation of the output image in a new figure.
Returns the numeric status code and text output from the unix() command. Also returns the name of the expected output file from Mitsuba. Usage: [status, result, output] = RunMitsuba(sceneFile, isShow)
References InitializeRenderToolbox(), MultispectralToSRGB(), ReadMultispectralEXR(), and ShowXYZAndSRGB().
Referenced by BatchRender().
status result output RunPBRT (sceneFile , isShow)
Invoke the PBRT renderer.
Parameters
sceneFile filename or path of a .pbrt scene file.
isShow whether or not to display the output image in a figure
Invoke the PBRT renderer on the given .pbrt sceneFile. This function handles some of the boring details of invoking PBRT with Matlab's unix() command.
if isShow is provided and true, displays an sRGB representation of the output image in a new figure.
Returns the numeric status code and text output from the unix() command. Also returns the name of the expected output file from PBRT. Usage: [status, result, output] = RunPBRT(sceneFile, isShow)
References InitializeRenderToolbox(), MultispectralToSRGB(), ReadDAT(), and ShowXYZAndSRGB().
Referenced by BatchRender().
ShowXYZAndSRGB (XYZImage , SRGBImage , name)
Plot XYZ and sRGB image representations.
Parameters
XYZImage image matrix with XYZ color data
SRGBImage image matrix with sRGB color data
name a name to give the images (optional)
Quick plotter for XYZ and sRGB image representations. The given XYZImage and SRGB image will be plotted in new figures. If name is provided, it will appear as the image title. This might help distinguish similar plots.
Usage: ShowXYZAndSRGB(XYZImage, SRGBImage, name)
Referenced by RunMitsuba(), and RunPBRT().
nX nY nZ edges ShowXYZHistogram (XYZImage , nEdges)
Plot histograms for XYZ image components.
Parameters
XYZImage matrix of XYZ image data
nEdges how many bin edges to use in histograms
Plots histograms of X, Y, and Z components of the given XYZimage, in a new figure. XYZimage should be in Psychtoolbox "Image" format (as opposed to "Calibration" format), with size [nY, nX, 3].
By default, plots histograms with 100 bin edges. If nEdges is provided, uses the given number of bin edges. All components will share the same bin edges, ranging from a common minimum to a commpn maximum. 0-values are ignored.
Returns the bin frequency counts for each component, X, Y, and Z. Also returns the array of bin edges.
Usage: [nX, nY, nZ, edges] = ShowXYZHistogram(XYZImage, nEdges)
vector StringToVector (string)
Convert a string representation of numbers to a 1D matrix.
Parameters
string a string with numeric representations
Scans the given string for integer or decimal numeric representations, and converts them to numeric form.
Returns a 1-dimensional double matrix containing the numbers represented in . If string is not a string, returns the string as it is.
Usage: vector = StringToVector(string)
Referenced by ApplyMitsubaObjects(), BatchRender(), ConvertGeometry(), ConvertLight(), ConvertMaterial(), ConvertNode(), GenericObjectsToPBRT(), PrintPBRTStatement(), ReadStringNumbers(), SetSceneValue(), WriteDefaultMappingsFile(), and WritePBRTFile().
string VectorToString (vector)
Convert a 1D matrix of numbers to string representation.
Parameters
vector numeric 1-dimensional matrix
Prints the given vector to a string with space-separated decimal representations. If all elements of the vector are integers, prints integer representations. Treats vector as 1-dimensional.
Returns a string that contains representations of all the elements of vector. If vector is not numeric, returns the vector as it is.
Usage: string = VectorToString(vector)
Referenced by AddParameter(), AddTransform(), GenericObjectsToPBRT(), PrintPBRTStatement(), ReadStringNumbers(), SetSceneValue(), WriteConditionsFile(), and WritePBRTFile().
gammaImage rawImage XYZToSRGB (XYZImage , toneMapFactor , toneMapMax , isScale)
Convert an image in XYZ colors to sRGB colors.
Parameters
XYZImage matrix of XYZ image data
toneMapFactor relative luminance truncation (optional)
toneMapMax absolute luminance truncation (optional)
isScale whether or not to scale in gamma correction (optional)
Converts an image in XYZ colors to sRGB colors, using a few Psychtoolbox functions. The given XYZ image should be a matrix of size [height width n] with XYZ color data. If toneMapFactor is greater than 0, truncates luminance above this factor times the mean luminance. If toneMapMax is greater than 0, truncates luminance above this fixed value. If isScale is true, the gamma-corrected image will be scaled to use the gamma-corrected maximum. Returns a matrix of size [height width n] with gamma corrected sRGB color data. Also returns a matrix of the same size with uncorrected sRGB color data.
Usage: [gammaImage, rawImage] = XYZToSRGB(XYZImage, toneMapFactor, toneMapMax, isScale)
Referenced by MakeMontage(), and MultispectralToSRGB().