Render Toolbox 3: Batch Renderer
Batch Renderer
Render scenes multiple times with changing variables.
Functions
outFiles BatchRender (sceneFile, conditionsFile, mappingsFile, hints)
Render a scene multiple times, with changing varibles.
hints GetDefaultHints (hints)
Get default hints to pass to the batch renderer.
SRGBMontage XYZMontage MakeMontage (inFiles, outFile, toneMapFactor, isScale, hints)
Condense several multi-spectral images into one sRGB montage.
ApplySceneDOMPaths (idMap, mappings)
Modify a scene document with a mapping.
names values ParseConditions (conditionsFile)
Read conditions data from a text file.
mappings ParseMappings (mappingsFile)
Read mappings data from a text file.
conditionsFile WriteConditionsFile (conditionsFile, names, values)
Write conditions data to a text file.
mappingsFile WriteDefaultMappingsFile (colladaFile, mappingsFile, includeFile, reflectances, lightSpectra, excludePattern)
Write a default mappings file for the given Collada scene file.
mappedScene mappedAdjust WriteMappedSceneFiles (workingPath, name, originalScene, originalAdjust, mappings, varNames, varValues, hints)
Apply condition values and mappings to scene and adjustments files.
Detailed Description
Render scenes multiple times with changing variables.
These functions make up the RenderToolox3 batch renderer, which can render the same basic scene multiple times, with changing variables. Users should not use most of these functions directly. Just use the BatchRender() and MakeMontage() functions.
Function Documentation
outFiles BatchRender (sceneFile , conditionsFile , mappingsFile , hints)
Render a scene multiple times, with changing varibles.
Parameters
sceneFile file name or path of a Collada scene file
conditionsFile file name or path of a conditions file
mappingsFile file name or path of a mappings file
hints struct of options for the batch renderer
Renders a scene multiple times, with variable values changing each time. Uses Scene DOM functions and Scene Target functions to apply variable values to the Collada sceneFile and renderer-specific adjustments files. Values for each condition come from the given conditionsFile. The mappingsFile specifies how to apply variables to the scene.
sceneFile must be a Collada XML scene file. sceneFile may be left empty, if the conditionsFile contains a 'sceneFile' variable.
conditionsFile must be a RenderToolbox3 Conditions File. conditionsFile may be omitted or left empty, if the scene is to be rendered only once.
mappingsFile must be a RenderToolbox3 Mappings File. mappingsFile may be omitted or left empty, if the scene is to be rendered only once, or if the conditionsFile contains a 'mappingsFile' variable.
hints may be a struct with options that affect the rendering process, as returned from GetDefaultHints(). If hints is omitted, default options are used. hints specifies which renderer to use.
Renders the scene one or more times, and writes a .mat file each time. The .mat file will contain multi-spectral renderer output in two variables:
multispectralImage - matrix of multispectral image data with size [height width n]
S - spectral plane description, [start delta n]
where height and width are pixel image dimensions and n is the number of spectral bands in the image. See the RenderToolbox3 wikiw for more about Spectrum Bands.
The .mat file will also contain variables with data about how the scene was rendered:
sceneFile - the given sceneFile, if any
conditionsFile - the given conditionsFile, if any
mappingsFile - the given mappingsFile, if any
hints - the given hints struct, or default hints struct
versionInfo - struct of version information about RenderToolbox3 and its dependencies
By default, each .mat file will have the same base name as sceneFile, plus a numeric suffix. If conditionsFile contains an 'imageName' variable, each ouput file be named with the value of 'imageName'.
Returns a cell array of string output file names, or an empty cell if no output.
Usage: outFiles = BatchRender(sceneFile, conditionsFile, mappingsFile, hints)
References ColladaToMitsuba(), ColladaToPBRT(), GetDefaultHints(), InitializeRenderToolbox(), ParseConditions(), ParseMappings(), ReadDAT(), ReadMultispectralEXR(), RenderToolboxRoot(), RunMitsuba(), RunPBRT(), StringToVector(), WriteASCII7BitOnly(), WriteMappedSceneFiles(), and WriteReducedColladaScene().
hints GetDefaultHints (hints)
Get default hints to pass to the batch renderer.
Parameters
hints partial struct of batch renderer options (optional)
Creates a struct of options for the batch renderer to use, or fills in missing parts of a the given hints struct. Batch renderer options include things like renderer name, image film size, and whether or not to delete intermediate files used in the batch rendering process.
If provided, hints should be a struct of renderer options with option names as fields. Fills in any missing options with default values. If hints is missing or not a struct, creates a new struct with all default values.
Hints can also be set using the global variable RENDER_TOOBLOX3_HINTS. If it exists, RENDER_TOOBLOX3_HINTS should be a full or partial struct of renderer options with the same fields as hints. The returned struct will contain, in order of preference, values in the given hints, values in RENDER_TOOBLOX3_HINTS, or default values.
Returns a new or modified struct of batch renderer options. output.
Usage: hints = GetDefaultHints(hints)
References IsStructFieldPresent(), and RenderToolboxRoot().
Referenced by BatchRender(), ColladaToMitsuba(), ColladaToPBRT(), MakeMontage(), and WritePBRTFile().
SRGBMontage XYZMontage MakeMontage (inFiles , outFile , toneMapFactor , isScale , hints)
Condense several multi-spectral images into one sRGB montage.
Parameters
inFiles cell array of input .mat file names
outFile output montage file name (optional)
toneMapFactor how to truncate montage luminance (optional)
isScale whether or not to scale montage luminance (optional)
hints struct of options for the montage maker
Condenses several multi-spectral images stored in .mat files into a single sRGB montage. Tiles the input images so that the montage has roughly the same aspect ratio as the input images.
Attempts to conserve system memory by loading only one multi-spectral image at a time.
inFiles must be a cell array of .mat file names, each of which must contain multi-spectral renderer output. BatchRender() returns such a cell array.
outFile determines where the montage is saved, and may include a path. The extension of outFile determines how the montage is saved:
The default is '.mat', in which case the montage XYZ and sRGB matrices are is saved to a new .mat file
If the extension matches a standard image format, like '.tiff' or '.png', the sRGB image will be saved in that format with Matlab's built-in imwrite().
If toneMapFactor is provided and greater than 0, montage luminances will be truncated above this factor times the mean luminance of the entire montage.
If isScale is provided and true, montage luminances will be scaled so that the maximum input luminance matches the maximum possible output luminance.
hints may be a struct with options that affect the montage, such as the output folder, as returned from GetDefaultHints(). If hints is omitted, default options are used.
Returns a matrix containing the tone mapped, scaled, sRGB montage with size [height width 3]. Also returns a matrix containing XYZ image data with the same size.
Usage: [SRGBMontage, XYZMontage] = MakeMontage(inFiles, outFile, toneMapFactor, isScale, hints)
References GetDefaultHints(), MultispectralToSRGB(), and XYZToSRGB().
ApplySceneDOMPaths (idMap , mappings)
Modify a scene document with a mapping.
Parameters
idMap
mappings
Modify the document represented by the given idMap, with the given mappings. mappings must be a struct array of mappings data as returned from ParseMappings(). The mappings should contain Scene DOM paths on the left-hand side.
Creates document nodes as needed, to satisfy the left-hand Scene DOM paths.
Used internally by BatchRender().
Usage: ApplySceneDOMPaths(idMap, mappings)
References CreateElementChild(), PathStringToCell(), and SetSceneValue().
names values ParseConditions (conditionsFile)
Read conditions data from a text file.
Parameters
conditionsFile
Reads batch renderer condition variables from the given conditionsFile. See the RenderToolbox3 wiki for more about Conditions Files.
Returns a 1 x n cell array of string variable names from the first line of conditionsFile. Also returns an m x n cell array of varible values, with m values per variable.
Used internally by BatchRender().
Usage: [names, values] = ParseConditions(conditionsFile)
Referenced by BatchRender().
mappings ParseMappings (mappingsFile)
Read mappings data from a text file.
Parameters
mappingsFile
Reads batch renderer mappings from the given mappingsFile. See the RenderToolbox3 wiki for more about Mappings Files.
Returns a 1xn struct array with mapping data. The struct array will have one element per mapping, and the following fields:
text - raw text before parsing
blockType - block type, 'Collada', 'Generic', 'Mitsuba', or 'PBRT'
blockNumber - the order of the block in the mappings file
group - name of a set of related blocks
left - a struct of info about the left-hand string
operator - the operator string
right - a struct of info about the right-hand string
Each 'left' or 'right' field will contain a struct with data about a string, with the following fields
text - the raw text before parsing
enclosing - the enclosing brackets, if any, '[]', '<>', or ''
value - the text found within enclising brackets
Used internally by BatchRender().
Usage: mappings = ParseMappings(mappingsFile)
Referenced by BatchRender().
conditionsFile WriteConditionsFile (conditionsFile , names , values)
Write conditions data to a text file.
Parameters
conditionsFile name of new text file to write.
names 1 x n cell array of string variable names
values m x n cell array of variable values
Writes batch renderer condition variables with the given names and values to a new text file with the given conditionsFile name. See the RenderToolbox3 wiki for more about Conditions Files.
names will appear in the first line of the new file, separated by tabs. Each of the m rows of values will appear in a separate line, with elements separated by tabs. So, the values for each variable will appear in a tab-separated column.
Attempts to convert numeric values to string, as needed.
Usage: conditionsFile = WriteConditionsFile(conditionsFile, names, values)
References VectorToString().
mappingsFile WriteDefaultMappingsFile (colladaFile , mappingsFile , includeFile , reflectances , lightSpectra , excludePattern)
Write a default mappings file for the given Collada scene file.
Parameters
colladaFile file name or path of the Collada scene file
mappingsFile file name or path for a new mappings file
includeFile file name or path for a mappings file to include
reflectances cell array of matte material reflectances
lightSpectra cell array of light source spectra
excludePattern regular expression to filter document elements
Traverses the Collada document in the given colladaFile and writes a new mappingsFile suitable for use with BatchRender(). The mappingsFile will specify default values, including:
mappings text in includeFile or RenderData/DefaultMappings.txt
matte material for each geometry node
a spectrum for each light source
Each material or light source will use a spectrum from a default list, or a provided list.
By default, prepends the text of RenderData/DefaultMappings.txt to the new mappings file. If includeFile is provided it must specify another text file to prepend instead.
By default, each matte material will use one of the Color Checker reflectance spectrums found in RenderData/Macbeth-ColorChecker. If reflectances is provided, it must be a cell array of string reflectance values to use instead.
By default, each light source will use the D65 light spectrum found in RenderData/D65.spd. If lightSpectra is provided, it must be a cell array of string spectrum values to use instead.
By default, writes mappings for all materials and light sources. If excludePattern is provided, it must be a regular expression to match against element id attributes. Elements whose ids match excludePattern will be excluded from the mappingsFile.
Returns the name of the new mappingsFile.
Usage: WriteDefaultMappingsFile(colladaFile, mappingsFile, includeFile, reflectances, lightSpectra, excludePattern)
References FindFiles(), GetColladaLightType(), ReadSceneDOM(), RenderToolboxRoot(), StringToVector(), WriteASCII7BitOnly(), and WriteReducedColladaScene().
mappedScene mappedAdjust WriteMappedSceneFiles (workingPath , name , originalScene , originalAdjust , mappings , varNames , varValues , hints)
Apply condition values and mappings to scene and adjustments files.
Parameters
workingPath
name
originalScene
originalAdjust
mappings
varNames
varValues
Apply variable values and mappings to scene and adjustments files.
workingPath must be a folder path name where to put new files. name must be a string name to include in the mapped scene file names.
originalScene and originalAdjust must be XML scene and adjustments files, respectively. originalAdjust is optional.
mappings must be a struct array of mapping data as returned from ParseMappings().
varNames and varValues must be cell arrays of variable names and corresponding values, as returned from ParseConditions().
hints should be a struct with renderer options. hints.renderer should be the name of a renderer, either 'Mitsuba', or 'PBRT'.
Writes copies of the given originalScene file and originalAdjustments file, and modifies each as specified by the given mappings, varNames, and varValues.
Returns the names of the new, mapped scene file and the new, mapped adjustments file.
Used internally by BatchRender().
Usage: [mappedScene, mappedAdjust] = WriteMappedSceneFiles(... workingPath, name, originalScene, originalAdjust, ... mappings, varNames, varValues, hints)
References ReadSceneDOM().
Referenced by BatchRender().